version: '3'

services:
    app_springboot:
        build: springboot
        ports:
            - "8080:8080"
        environment:
            PYTHON_API_URL: "http://app_api:5000"
            DATA_BASE_URL: ${DATA_BASE_URL}
            DATA_BASE_USERNAME: ${DATA_BASE_USERNAME}
            DATA_BASE_PASSWORD: ${DATA_BASE_PASSWORD}
            EXPIRATION_TIME: ${EXPIRATION_TIME}
            CLOUDINARY_URL: ${CLOUDINARY_URL}
        depends_on:
            app_api:
                condition: service_healthy

    app_api:
        build: flaskAPI
        ports:
            -"5000:5000"
        environment:
            DATA_BASE_URL: ${DATA_BASE_URL}
            DATA_BASE_USERNAME: ${DATA_BASE_USERNAME}
            DATA_BASE_PASSWORD: ${DATA_BASE_PASSWORD}