version: '3'

services:
  springboot:
    build: springboot
    ports:
      - "8080:8080"
    environment:
      API_URL_BASE: "http://api:5000/"
      DATA_BASE_URL: ${DATA_BASE_URL}
      DATA_BASE_USERNAME: ${DATA_BASE_USERNAME}
      DATA_BASE_PASSWORD: ${DATA_BASE_PASSWORD}
      EXPIRATION_TIME: ${EXPIRATION_TIME}
      CLOUDINARY_URL: ${CLOUDINARY_URL}
    restart: on-failure
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          memory: 1g

  api:
    build: flaskAPI
    ports:
      - "5000:5000"
    environment:
      API_Pixabay: ${API_Pixabay}
      API_Qroq: ${API_Qroq}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
    restart: on-failure
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 6g

networks:
  mynetwork:
    driver: bridge
